---
driver:
  name: vagrant

driver_config:
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.3.0
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[jenkins-simple-app::default]
    attributes:
      jenkins_simple_app:
        git_repository_url: http://github.com/CatCalZone/jenkins-jobs.git
