<%
def box_for_provider(distro)
  case ENV.fetch('VAGRANT_DEFAULT_PROVIDER', 'virtualbox')
    when 'virtualbox' then "bento/#{distro}"
    when 'docker' then "tknerr/baseimage-#{distro}"
    else raise 'unsupported provider!'
  end
end
%>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.4.1
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  client_rb:
    add_formatter: doc

platforms:
- name: ubuntu-14.04
  driver_config:
    box: <%= box_for_provider('ubuntu-14.04') %>
    network:
      - ["forwarded_port", {guest: 8080, host: 8080}]

suites:
  - name: default
    run_list:
      - recipe[jenkins-simple-app::default]
    attributes:
      jenkins_simple_app:
        git_repository_url: http://github.com/CatCalZone/jenkins-jobs.git

  - name: java_slave
    run_list:
      - recipe[jenkins-simple-app::java_slave]
