name 'jenkins-simple-app'
maintainer 'Torben Knerr'
maintainer_email 'torben.knerr@zuehlke.com'
source_url 'https://github.com/Zuehlke/cookbooks-jenkins-simple-app'
issues_url 'https://github.com/Zuehlke/cookbooks-jenkins-simple-app/issues'
license 'mit'
description 'Installs/Configures jenkins-simple-app'
long_description 'Installs/Configures jenkins-simple-app'
version '0.1.0'

depends 'jenkins', '2.5.0'
depends 'git', '4.5.0'
depends 'apt', '2.9.2'
