name 'jenkins-simple-app'
maintainer 'Torben Knerr'
maintainer_email 'torben.knerr@zuehlke.com'
license 'mit'
description 'Installs/Configures jenkins-simple-app'
long_description 'Installs/Configures jenkins-simple-app'
version '0.1.0'

depends 'jenkins', '2.3.1'
depends 'git', '4.2.2'
